# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MediaPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border-radius:10px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cadre = QtWidgets.QFrame(self.centralwidget)
        self.cadre.setStyleSheet("border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.493, y1:0, x2:0.492925, y2:0.972, stop:0 rgba(24, 37, 54, 255), stop:1 rgba(81, 88, 100, 255));\n"
"")
        self.cadre.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cadre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cadre.setObjectName("cadre")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cadre)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Top = QtWidgets.QFrame(self.cadre)
        self.Top.setMinimumSize(QtCore.QSize(930, 40))
        self.Top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.493, y1:0, x2:0.492925, y2:0.972, stop:0 rgba(24, 37, 54, 255), stop:1 rgba(81, 88, 100, 255))")
        self.Top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top.setObjectName("Top")
        self.pushButton_close = QtWidgets.QPushButton(self.Top)
        self.pushButton_close.setGeometry(QtCore.QRect(10, 5, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(10)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"border: 1px solid rgb(85, 0, 0);")
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_close_2 = QtWidgets.QPushButton(self.Top)
        self.pushButton_close_2.setGeometry(QtCore.QRect(60, 5, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(10)
        self.pushButton_close_2.setFont(font)
        self.pushButton_close_2.setStyleSheet("\n"
"background-color: rgb(85, 170, 255);\n"
"border: 1px solid blue;")
        self.pushButton_close_2.setObjectName("pushButton_close_2")
        self.verticalLayout_2.addWidget(self.Top)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu_left = QtWidgets.QFrame(self.cadre)
        self.menu_left.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_left.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_left.setStyleSheet("background-color:rgb(64, 69, 79);\n"
"border: 1px solid black;\n"
"")
        self.menu_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_left.setObjectName("menu_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu_left)
        self.verticalLayout_3.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.video = QtWidgets.QPushButton(self.menu_left)
        self.video.setMinimumSize(QtCore.QSize(70, 70))
        self.video.setMaximumSize(QtCore.QSize(16777215, 100))
        self.video.setStyleSheet("\n"
"QPushButton:hover{\n"
"background-color:rgb(62, 62, 150);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.89, fx:0.5, fy:0.5, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(93, 93, 93, 255));\n"
"}\n"
"")
        self.video.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icones/icones/media/HP-Video-Folder-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.video.setIcon(icon)
        self.video.setIconSize(QtCore.QSize(65, 69))
        self.video.setAutoDefault(True)
        self.video.setObjectName("video")
        self.verticalLayout_3.addWidget(self.video)
        self.picture = QtWidgets.QPushButton(self.menu_left)
        self.picture.setMinimumSize(QtCore.QSize(70, 70))
        self.picture.setMaximumSize(QtCore.QSize(16777215, 100))
        self.picture.setStyleSheet("\n"
"QPushButton:hover{\n"
"background-color:rgb(62, 62, 150);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.89, fx:0.5, fy:0.5, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(93, 93, 93, 255));\n"
"}\n"
"")
        self.picture.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icones/icones/media/HP-Pictures-Folder-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.picture.setIcon(icon1)
        self.picture.setIconSize(QtCore.QSize(63, 61))
        self.picture.setAutoDefault(True)
        self.picture.setObjectName("picture")
        self.verticalLayout_3.addWidget(self.picture)
        self.audio = QtWidgets.QPushButton(self.menu_left)
        self.audio.setMinimumSize(QtCore.QSize(70, 70))
        self.audio.setMaximumSize(QtCore.QSize(16777215, 100))
        self.audio.setStyleSheet("\n"
"QPushButton:hover{\n"
"background-color:rgb(62, 62, 150);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.89, fx:0.5, fy:0.5, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(93, 93, 93, 255));\n"
"}\n"
"")
        self.audio.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icones/icones/media/HP-Music-Folder-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audio.setIcon(icon2)
        self.audio.setIconSize(QtCore.QSize(67, 63))
        self.audio.setAutoDefault(True)
        self.audio.setObjectName("audio")
        self.verticalLayout_3.addWidget(self.audio)
        self.config = QtWidgets.QPushButton(self.menu_left)
        self.config.setMinimumSize(QtCore.QSize(70, 70))
        self.config.setMaximumSize(QtCore.QSize(16777215, 100))
        self.config.setStyleSheet("\n"
"QPushButton:hover{\n"
"background-color:rgb(62, 62, 150);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.89, fx:0.5, fy:0.5, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(93, 93, 93, 255));\n"
"}\n"
"")
        self.config.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icones/icones/media/gear-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.config.setIcon(icon3)
        self.config.setIconSize(QtCore.QSize(66, 67))
        self.config.setAutoDefault(True)
        self.config.setObjectName("config")
        self.verticalLayout_3.addWidget(self.config)
        self.label_2 = QtWidgets.QLabel(self.menu_left)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.menu_left)
        self.screen = QtWidgets.QFrame(self.cadre)
        self.screen.setMinimumSize(QtCore.QSize(0, 0))
        self.screen.setStyleSheet("background-color: rgb(0, 0,0);")
        self.screen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.screen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.screen.setObjectName("screen")
        self.horizontalLayout_2.addWidget(self.screen)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.play = QtWidgets.QPushButton(self.cadre)
        self.play.setMinimumSize(QtCore.QSize(60, 30))
        self.play.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(9)
        self.play.setFont(font)
        self.play.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"border: 1px solid rgb(68, 0, 102);\n"
"    background-color: rgb(211, 199, 255);\n"
"}")
        self.play.setText("")
        self.play.setObjectName("play")
        self.gridLayout.addWidget(self.play, 0, 0, 1, 1)
        self.stop = QtWidgets.QPushButton(self.cadre)
        self.stop.setMinimumSize(QtCore.QSize(60, 0))
        self.stop.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Wingdings 2")
        font.setPointSize(9)
        self.stop.setFont(font)
        self.stop.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"border: 1px solid rgb(68, 0, 102);\n"
"    background-color: rgb(211, 199, 255);\n"
"}")
        self.stop.setText("")
        self.stop.setObjectName("stop")
        self.gridLayout.addWidget(self.stop, 0, 1, 1, 1)
        self.prev = QtWidgets.QPushButton(self.cadre)
        self.prev.setMinimumSize(QtCore.QSize(60, 30))
        self.prev.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(9)
        self.prev.setFont(font)
        self.prev.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"border: 1px solid rgb(68, 0, 102);\n"
"    background-color: rgb(211, 199, 255);\n"
"}")
        self.prev.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icones/icones/media/Media-Controls-Skip-To-Start-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev.setIcon(icon4)
        self.prev.setObjectName("prev")
        self.gridLayout.addWidget(self.prev, 0, 2, 1, 1)
        self.next = QtWidgets.QPushButton(self.cadre)
        self.next.setMinimumSize(QtCore.QSize(60, 30))
        self.next.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(9)
        self.next.setFont(font)
        self.next.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"border: 1px solid rgb(68, 0, 102);\n"
"    background-color: rgb(211, 199, 255);\n"
"}")
        self.next.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icones/icones/media/Media-Controls-End-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon5)
        self.next.setObjectName("next")
        self.gridLayout.addWidget(self.next, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.cadre)
        self.label.setMaximumSize(QtCore.QSize(28, 28))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icones/icones/media/Media-Controls-Volume-Down-icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.slider_vol = QtWidgets.QSlider(self.cadre)
        self.slider_vol.setMinimumSize(QtCore.QSize(100, 0))
        self.slider_vol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.slider_vol.setStyleSheet("QSlider{\n"
"border: 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(170, 0, 255, 255), stop:1 rgba(170, 170, 255, 255));\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.slider_vol.setMaximum(1200)
        self.slider_vol.setProperty("value", 123)
        self.slider_vol.setOrientation(QtCore.Qt.Horizontal)
        self.slider_vol.setObjectName("slider_vol")
        self.gridLayout.addWidget(self.slider_vol, 0, 5, 1, 1)
        self.lbl_vol = QtWidgets.QLabel(self.cadre)
        self.lbl_vol.setMinimumSize(QtCore.QSize(0, 15))
        self.lbl_vol.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_vol.setFont(font)
        self.lbl_vol.setStyleSheet("background-color:transparent ;\n"
"color:white;")
        self.lbl_vol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_vol.setObjectName("lbl_vol")
        self.gridLayout.addWidget(self.lbl_vol, 0, 6, 1, 1)
        self.slider_position = QtWidgets.QSlider(self.cadre)
        self.slider_position.setMinimumSize(QtCore.QSize(600, 0))
        self.slider_position.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.slider_position.setStyleSheet("QSlider{\n"
"border: 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 15px;\n"
"border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.slider_position.setMaximum(1200)
        self.slider_position.setProperty("value", 123)
        self.slider_position.setOrientation(QtCore.Qt.Horizontal)
        self.slider_position.setObjectName("slider_position")
        self.gridLayout.addWidget(self.slider_position, 0, 7, 1, 1)
        self.lbl_temps = QtWidgets.QLabel(self.cadre)
        self.lbl_temps.setMinimumSize(QtCore.QSize(0, 15))
        self.lbl_temps.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_temps.setFont(font)
        self.lbl_temps.setStyleSheet("background-color:transparent ;\n"
"color:white;")
        self.lbl_temps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_temps.setObjectName("lbl_temps")
        self.gridLayout.addWidget(self.lbl_temps, 0, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.cadre)
        self.label_4.setMinimumSize(QtCore.QSize(0, 15))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:transparent ;\n"
"color:white;")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 9, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.cadre)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_close.setText(_translate("MainWindow", "r"))
        self.pushButton_close_2.setText(_translate("MainWindow", "1"))
        self.lbl_vol.setText(_translate("MainWindow", "12%"))
        self.lbl_temps.setText(_translate("MainWindow", "00::00:00  "))
        self.label_4.setText(_translate("MainWindow", "00::00:00  "))
import media_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
